# Generated by Django 3.0.3 on 2020-04-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'managed': True},
        ),
    ]
