# Generated by Django 3.0.3 on 2020-04-15 22:13

from django.db import migrations
import csv


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]

    def add_city_data(apps, schema_editor):
        file = open('golfersInput.csv', 'r')
        lines = csv.reader(file)
        golfers_list = list(lines)
        for golfer in golfers_list:
            golfer_name = golfer[0].strip('')
            birthdate = golfer[1].strip('')
            golfer_city = golfer[2].strip('')
        file.close()

        Golfer = apps.get_model('golfer', 'Golfer')
        for name, bdate, city in golfers_list:
            golfer = Golfer.objects.get(golfer_name= name)
            golfer.golfer_city=city
            golfer.save()


    def remove_city_data(apps, schema_editor):
        Golfer = apps.get_model('golfer', 'Golfer')
        Golfer.objects.update(golfer_city='unknown')

    operations = [
        migrations.RunPython(add_city_data, reverse_code=remove_city_data)
    ]
